name: custom_elements
version: 0.0.4
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
description: Custom Elements from Community ported to dart
homepage: https://www.drafintech.it
dependencies:
  polymer_interop: ^1.0.0-rc.5
  web_components: ^0.12.0
  polymer_elements: ^1.0.0-rc.5
dev_dependencies:
  browser: ^0.10.0
  custom_element_apigen: ^0.2.1+1
  html5lib: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  polymer: ^1.0.0-rc.6
  reflectable: ">=0.3.1 <0.5.0"
  test: ^0.12.5+1
  yaml: ">=1.0.0 <3.0.0"

# NOTE : Need to uncomment this to run the correct upgrade
#dependency_overrides:
# custom_element_apigen:
#  git: git@github.com:dam0vm3nt/custom-element-apigen.git
#  path: ../custom-element-apigen


environment:
  sdk: ">=1.8.0 <2.0.0"
